sliders=SHADOW_BIAS SHADOW_DISTORT_FACTOR SHADOW_BRIGHTNESS shadowMapResolution BLUE_AMOUNT GREEN_AMOUNT GRAY_AMOUNT TERRAIN_GRAY_AMOUNT TORCH_R TORCH_G TORCH_B

screen=BLUE_AMOUNT GREEN_AMOUNT GRAY_AMOUNT BLACK_SKY RED_SUN GREEN_CLOUDS RED_ENTITIES TERRAIN_GRAY_AMOUNT LIGHTING_STYLE TORCH_R TORCH_G TORCH_B